import { networkType } from "../networkType.js";
import { TestNetAbis } from "./testNetUpdatedAbi.js";

let abi = "";
if (networkType === "testnet") {
  abi = [
    {
      constant: true,
      inputs: [{ name: "interfaceId", type: "bytes4" }],
      name: "supportsInterface",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "name",
      outputs: [{ name: "", type: "string" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "cancelSell",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "getApproved",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "to", type: "address" },
        { name: "tokenId", type: "uint256" },
      ],
      name: "approve",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "owner", type: "address" },
        { name: "tokenId", type: "uint256" },
      ],
      name: "transferFromAdmin",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "tokenId", type: "uint256" },
        { name: "newPrice", type: "uint256" },
        { name: "newDollarPrice", type: "uint256" },
      ],
      name: "updatePrice",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "stringId", type: "string" },
        { name: "amount", type: "uint256" },
      ],
      name: "updateAliaBalance",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "totalSupply",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "tokenIdT", type: "uint256" },
        { name: "uriT", type: "string" },
      ],
      name: "updateTokenURI",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "", type: "address" }],
      name: "_supportNft",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "from", type: "address" },
        { name: "to", type: "address" },
        { name: "tokenId", type: "uint256" },
      ],
      name: "transferFrom",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "_contract", type: "address" },
        { name: "_tokenId", type: "uint256" },
        { name: "_minPrice", type: "uint256" },
        { name: "priceDollar", type: "uint256" },
        { name: "_endTime", type: "uint256" },
      ],
      name: "setOnAuction",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "owner", type: "address" },
        { name: "index", type: "uint256" },
      ],
      name: "tokenOfOwnerByIndex",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "tokenId", type: "uint256" },
        { name: "sellerId", type: "string" },
        { name: "price", type: "uint256" },
        { name: "priceDollar", type: "uint256" },
      ],
      name: "sellNFTNonCrypto",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "from", type: "address" },
        { name: "to", type: "address" },
        { name: "tokenId", type: "uint256" },
      ],
      name: "safeTransferFrom",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "platform",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "_tokenId", type: "uint256" },
        { name: "bidAddr", type: "address" },
        { name: "_amount", type: "uint256" },
      ],
      name: "updateBidder",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "nft_a", type: "address" },
        { name: "tokenId", type: "uint256" },
        { name: "ownerId", type: "string" },
      ],
      name: "buyNFT",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "index", type: "uint256" }],
      name: "tokenByIndex",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "_tokenId", type: "uint256" },
        { name: "_amount", type: "uint256" },
        { name: "awardType", type: "bool" },
        { name: "from", type: "address" },
      ],
      name: "placeBid",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "ownerOf",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "", type: "uint256" }],
      name: "_royality",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "price", type: "uint256" },
        { name: "from", type: "address" },
      ],
      name: "mintAliaForNonCrypto",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "allTokens",
      outputs: [{ name: "", type: "uint256[]" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "owner", type: "address" }],
      name: "balanceOf",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "renounceOwnership",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "nonCryptoNFTVault",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "ownerId", type: "string" }],
      name: "getNonCryptoWallet",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "owner", type: "address" }],
      name: "tokensOfOwner",
      outputs: [{ name: "", type: "uint256[]" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "owner",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "isOwner",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "symbol",
      outputs: [{ name: "", type: "string" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "account", type: "address" }],
      name: "addMinter",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "renounceMinter",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "getSellDetail",
      outputs: [
        { name: "", type: "address" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
        { name: "", type: "address" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "_tokenId", type: "uint256" },
        { name: "awardType", type: "bool" },
        { name: "ownerId", type: "string" },
        { name: "from", type: "address" },
      ],
      name: "claimAuction",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenIdFunction", type: "uint256" }],
      name: "getAuthor",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "to", type: "address" },
        { name: "approved", type: "bool" },
      ],
      name: "setApprovalForAll",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "init5",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "", type: "uint256" }],
      name: "sellList",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "account", type: "address" }],
      name: "isMinter",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "adminDiscount",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "to", type: "address" },
        { name: "tokenURI", type: "string" },
        { name: "quantity", type: "uint256" },
        { name: "flag", type: "bool" },
        { name: "price", type: "uint256" },
        { name: "ownerId", type: "string" },
        { name: "royality", type: "uint256" },
        { name: "priceDollar", type: "uint256" },
        { name: "_isArtist", type: "bool" },
      ],
      name: "MintAndSellNFT",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "nft_a", type: "address" },
        { name: "tokenId", type: "uint256" },
        { name: "seller", type: "address" },
        { name: "price", type: "uint256" },
        { name: "priceDollar", type: "uint256" },
      ],
      name: "sellNFT",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "from", type: "address" },
        { name: "to", type: "address" },
        { name: "tokenId", type: "uint256" },
        { name: "_data", type: "bytes" },
      ],
      name: "safeTransferFrom",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "getNonCryptoOwner",
      outputs: [{ name: "", type: "string" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "", type: "uint256" }],
      name: "_dollarPrice",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "to", type: "address" },
        { name: "tokenURI", type: "string" },
        { name: "quantity", type: "uint256" },
        { name: "flag", type: "bool" },
        { name: "_contract", type: "address" },
        { name: "_minPrice", type: "uint256" },
        { name: "ownerId", type: "string" },
        { name: "_endTime", type: "uint256" },
        { name: "royality", type: "uint256" },
        { name: "priceDollar", type: "uint256" },
      ],
      name: "MintAndAuctionNFT",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "tokenURI",
      outputs: [{ name: "", type: "string" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "onSell",
      outputs: [{ name: "", type: "uint256[]" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "", type: "address" }],
      name: "adminOwner",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "owner", type: "address" },
        { name: "operator", type: "address" },
      ],
      name: "isApprovedForAll",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "seller", type: "address" },
        { name: "tokenURI", type: "string" },
        { name: "flag", type: "bool" },
        { name: "to", type: "address" },
        { name: "ownerId", type: "string" },
      ],
      name: "blindBox",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "_discount", type: "uint256" }],
      name: "setAdminDiscount",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "newOwner", type: "address" }],
      name: "transferOwnership",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "authorVault",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "nft_a", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "seller", type: "address" },
        { indexed: false, name: "price", type: "uint256" },
        { indexed: false, name: "dollarPrice", type: "uint256" },
        { indexed: false, name: "royalty", type: "uint256" },
      ],
      name: "SellNFT",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "nft_a", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "buyer", type: "address" },
      ],
      name: "BuyNFT",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
      ],
      name: "CancelSell",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "newPrice", type: "uint256" },
        { indexed: false, name: "newDollarPrice", type: "uint256" },
      ],
      name: "UpdatePrice",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "seller", type: "address" },
        { indexed: false, name: "nftContract", type: "address" },
        { indexed: true, name: "tokenId", type: "uint256" },
        { indexed: false, name: "startPrice", type: "uint256" },
        { indexed: false, name: "priceDollar", type: "uint256" },
        { indexed: false, name: "endTime", type: "uint256" },
      ],
      name: "OnAuction",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "bidder", type: "address" },
        { indexed: false, name: "nftContract", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "amount", type: "uint256" },
        { indexed: false, name: "awardType", type: "bool" },
      ],
      name: "Bid",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "bidder", type: "address" },
        { indexed: false, name: "nftContract", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "amount", type: "uint256" },
        { indexed: false, name: "awardType", type: "bool" },
      ],
      name: "Claim",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "nft_a", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "buyer", type: "string" },
      ],
      name: "BuyNFTNonCrypto",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "nft_a", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "seller", type: "string" },
        { indexed: false, name: "price", type: "uint256" },
        { indexed: false, name: "dollarPrice", type: "uint256" },
      ],
      name: "SellNFTNonCrypto",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "to", type: "string" },
        { indexed: false, name: "tokenURI", type: "string" },
        { indexed: false, name: "quantity", type: "uint256" },
        { indexed: false, name: "flag", type: "bool" },
      ],
      name: "MintWithTokenURINonCrypto",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "nft_a", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "seller", type: "string" },
        { indexed: false, name: "startPrice", type: "uint256" },
        { indexed: false, name: "priceDollar", type: "uint256" },
        { indexed: false, name: "endTime", type: "uint256" },
      ],
      name: "awardAuctionNFT",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "to", type: "string" },
        { indexed: false, name: "tokenId", type: "uint256" },
      ],
      name: "TransferPackNonCrypto",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "to", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "uriT", type: "string" },
      ],
      name: "updateTokenEvent",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, name: "amount", type: "uint256" }],
      name: "updateDiscount",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "previousOwner", type: "address" },
        { indexed: true, name: "newOwner", type: "address" },
      ],
      name: "OwnershipTransferred",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "action", type: "string" },
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "to", type: "address" },
        { indexed: false, name: "tokenURI", type: "string" },
        { indexed: false, name: "quantity", type: "uint256" },
        { indexed: false, name: "flag", type: "bool" },
        { indexed: false, name: "token", type: "uint256" },
      ],
      name: "MintWithTokenURI",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, name: "account", type: "address" }],
      name: "MinterAdded",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, name: "account", type: "address" }],
      name: "MinterRemoved",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: true, name: "to", type: "address" },
        { indexed: true, name: "tokenId", type: "uint256" },
      ],
      name: "Transfer",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "owner", type: "address" },
        { indexed: true, name: "approved", type: "address" },
        { indexed: true, name: "tokenId", type: "uint256" },
      ],
      name: "Approval",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "owner", type: "address" },
        { indexed: true, name: "operator", type: "address" },
        { indexed: false, name: "approved", type: "bool" },
      ],
      name: "ApprovalForAll",
      type: "event",
    },
  ];
  abi = TestNetAbis;
} else if (networkType === "mainnet") {
  abi = [
    {
      constant: true,
      inputs: [{ name: "interfaceId", type: "bytes4" }],
      name: "supportsInterface",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "name",
      outputs: [{ name: "", type: "string" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "cancelSell",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "getApproved",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "to", type: "address" },
        { name: "tokenId", type: "uint256" },
      ],
      name: "approve",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "owner", type: "address" },
        { name: "tokenId", type: "uint256" },
      ],
      name: "transferFromAdmin",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "tokenId", type: "uint256" },
        { name: "newPrice", type: "uint256" },
        { name: "newDollarPrice", type: "uint256" },
      ],
      name: "updatePrice",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "totalSupply",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "tokenIdT", type: "uint256" },
        { name: "uriT", type: "string" },
      ],
      name: "updateTokenURI",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "", type: "address" }],
      name: "_supportNft",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "from", type: "address" },
        { name: "to", type: "address" },
        { name: "tokenId", type: "uint256" },
      ],
      name: "transferFrom",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "_contract", type: "address" },
        { name: "_tokenId", type: "uint256" },
        { name: "_minPrice", type: "uint256" },
        { name: "priceDollar", type: "uint256" },
        { name: "_endTime", type: "uint256" },
      ],
      name: "setOnAuction",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "owner", type: "address" },
        { name: "index", type: "uint256" },
      ],
      name: "tokenOfOwnerByIndex",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "tokenId", type: "uint256" },
        { name: "sellerId", type: "string" },
        { name: "price", type: "uint256" },
        { name: "priceDollar", type: "uint256" },
      ],
      name: "sellNFTNonCrypto",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "from", type: "address" },
        { name: "to", type: "address" },
        { name: "tokenId", type: "uint256" },
      ],
      name: "safeTransferFrom",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "platform",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "_tokenId", type: "uint256" },
        { name: "bidAddr", type: "address" },
        { name: "_amount", type: "uint256" },
      ],
      name: "updateBidder",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "nft_a", type: "address" },
        { name: "tokenId", type: "uint256" },
        { name: "ownerId", type: "string" },
      ],
      name: "buyNFT",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "index", type: "uint256" }],
      name: "tokenByIndex",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "_tokenId", type: "uint256" },
        { name: "_amount", type: "uint256" },
        { name: "awardType", type: "bool" },
        { name: "from", type: "address" },
      ],
      name: "placeBid",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "ownerOf",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "", type: "uint256" }],
      name: "_royality",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "price", type: "uint256" },
        { name: "from", type: "address" },
      ],
      name: "mintAliaForNonCrypto",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "allTokens",
      outputs: [{ name: "", type: "uint256[]" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "owner", type: "address" }],
      name: "balanceOf",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "renounceOwnership",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "nonCryptoNFTVault",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "ownerId", type: "string" }],
      name: "getNonCryptoWallet",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "owner", type: "address" }],
      name: "tokensOfOwner",
      outputs: [{ name: "", type: "uint256[]" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "owner",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "isOwner",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "symbol",
      outputs: [{ name: "", type: "string" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "account", type: "address" }],
      name: "addMinter",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "renounceMinter",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "getSellDetail",
      outputs: [
        { name: "", type: "address" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
        { name: "", type: "address" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "_tokenId", type: "uint256" },
        { name: "awardType", type: "bool" },
        { name: "ownerId", type: "string" },
        { name: "from", type: "address" },
      ],
      name: "claimAuction",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenIdFunction", type: "uint256" }],
      name: "getAuthor",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "to", type: "address" },
        { name: "approved", type: "bool" },
      ],
      name: "setApprovalForAll",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "init5",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "", type: "uint256" }],
      name: "sellList",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "account", type: "address" }],
      name: "isMinter",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "adminDiscount",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "to", type: "address" },
        { name: "tokenURI", type: "string" },
        { name: "quantity", type: "uint256" },
        { name: "flag", type: "bool" },
        { name: "price", type: "uint256" },
        { name: "ownerId", type: "string" },
        { name: "royality", type: "uint256" },
        { name: "priceDollar", type: "uint256" },
        { name: "_isArtist", type: "bool" },
      ],
      name: "MintAndSellNFT",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "nft_a", type: "address" },
        { name: "tokenId", type: "uint256" },
        { name: "seller", type: "address" },
        { name: "price", type: "uint256" },
        { name: "priceDollar", type: "uint256" },
      ],
      name: "sellNFT",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "from", type: "address" },
        { name: "to", type: "address" },
        { name: "tokenId", type: "uint256" },
        { name: "_data", type: "bytes" },
      ],
      name: "safeTransferFrom",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "getNonCryptoOwner",
      outputs: [{ name: "", type: "string" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "", type: "uint256" }],
      name: "_dollarPrice",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "to", type: "address" },
        { name: "tokenURI", type: "string" },
        { name: "quantity", type: "uint256" },
        { name: "flag", type: "bool" },
        { name: "_contract", type: "address" },
        { name: "_minPrice", type: "uint256" },
        { name: "ownerId", type: "string" },
        { name: "_endTime", type: "uint256" },
        { name: "royality", type: "uint256" },
        { name: "priceDollar", type: "uint256" },
      ],
      name: "MintAndAuctionNFT",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "tokenURI",
      outputs: [{ name: "", type: "string" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "onSell",
      outputs: [{ name: "", type: "uint256[]" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "", type: "address" }],
      name: "adminOwner",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "owner", type: "address" },
        { name: "operator", type: "address" },
      ],
      name: "isApprovedForAll",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "seller", type: "address" },
        { name: "tokenURI", type: "string" },
        { name: "flag", type: "bool" },
        { name: "to", type: "address" },
        { name: "ownerId", type: "string" },
      ],
      name: "blindBox",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "_discount", type: "uint256" }],
      name: "setAdminDiscount",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "newOwner", type: "address" }],
      name: "transferOwnership",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "authorVault",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "nft_a", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "seller", type: "address" },
        { indexed: false, name: "price", type: "uint256" },
        { indexed: false, name: "dollarPrice", type: "uint256" },
        { indexed: false, name: "royalty", type: "uint256" },
      ],
      name: "SellNFT",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "nft_a", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "buyer", type: "address" },
      ],
      name: "BuyNFT",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
      ],
      name: "CancelSell",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "newPrice", type: "uint256" },
        { indexed: false, name: "newDollarPrice", type: "uint256" },
      ],
      name: "UpdatePrice",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "seller", type: "address" },
        { indexed: false, name: "nftContract", type: "address" },
        { indexed: true, name: "tokenId", type: "uint256" },
        { indexed: false, name: "startPrice", type: "uint256" },
        { indexed: false, name: "priceDollar", type: "uint256" },
        { indexed: false, name: "endTime", type: "uint256" },
      ],
      name: "OnAuction",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "bidder", type: "address" },
        { indexed: false, name: "nftContract", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "amount", type: "uint256" },
        { indexed: false, name: "awardType", type: "bool" },
      ],
      name: "Bid",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "bidder", type: "address" },
        { indexed: false, name: "nftContract", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "amount", type: "uint256" },
        { indexed: false, name: "awardType", type: "bool" },
      ],
      name: "Claim",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "nft_a", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "buyer", type: "string" },
      ],
      name: "BuyNFTNonCrypto",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "nft_a", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "seller", type: "string" },
        { indexed: false, name: "price", type: "uint256" },
        { indexed: false, name: "dollarPrice", type: "uint256" },
      ],
      name: "SellNFTNonCrypto",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "to", type: "string" },
        { indexed: false, name: "tokenURI", type: "string" },
        { indexed: false, name: "quantity", type: "uint256" },
        { indexed: false, name: "flag", type: "bool" },
      ],
      name: "MintWithTokenURINonCrypto",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "nft_a", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "seller", type: "string" },
        { indexed: false, name: "startPrice", type: "uint256" },
        { indexed: false, name: "priceDollar", type: "uint256" },
        { indexed: false, name: "endTime", type: "uint256" },
      ],
      name: "awardAuctionNFT",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "to", type: "string" },
        { indexed: false, name: "tokenId", type: "uint256" },
      ],
      name: "TransferPackNonCrypto",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "to", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "uriT", type: "string" },
      ],
      name: "updateTokenEvent",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, name: "amount", type: "uint256" }],
      name: "updateDiscount",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "previousOwner", type: "address" },
        { indexed: true, name: "newOwner", type: "address" },
      ],
      name: "OwnershipTransferred",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "action", type: "string" },
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "to", type: "address" },
        { indexed: false, name: "tokenURI", type: "string" },
        { indexed: false, name: "quantity", type: "uint256" },
        { indexed: false, name: "flag", type: "bool" },
        { indexed: false, name: "token", type: "uint256" },
      ],
      name: "MintWithTokenURI",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, name: "account", type: "address" }],
      name: "MinterAdded",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, name: "account", type: "address" }],
      name: "MinterRemoved",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: true, name: "to", type: "address" },
        { indexed: true, name: "tokenId", type: "uint256" },
      ],
      name: "Transfer",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "owner", type: "address" },
        { indexed: true, name: "approved", type: "address" },
        { indexed: true, name: "tokenId", type: "uint256" },
      ],
      name: "Approval",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "owner", type: "address" },
        { indexed: true, name: "operator", type: "address" },
        { indexed: false, name: "approved", type: "bool" },
      ],
      name: "ApprovalForAll",
      type: "event",
    },
  ];
}

export default abi;
