export const ACCOUNT_KEY_SUCCESS = "ACCOUNT_KEY_SUCCESS";
export const ACCOUNT_KEY_FAIL = "ACCOUNT_KEY_FAIL";
export const RESET_ACCOUNT = "RESET_ACCOUNT";

export const LOAD_NFT_START = "LOAD_NFT_START";
export const NFT_LIST_SUCCESS = "NFT_LIST_SUCCESS";
export const NFT_LIST_FAIL = "NFT_LIST_FAIL";
export const NFT_LIST_UPDATE = "NFT_LIST_UPDATE";

export const PAGE_CHANGE = "PAGE_CHANGE";
export const MY_PAGE_CHANGE = "MY_PAGE_CHANGE";
export const HANDLE_LIKE_DISLIKE = "HANDLE_LIKE_DISLIKE";

export const MY_NFT_LOAD_START = "MY_NFT_LOAD_START";
export const MY_NFT_LOAD_SUCCESS = "MY_NFT_LOAD_SUCCESS";
export const MY_NFT_LOAD_FAIL = "MY_NFT_LOAD_FAIL";