export const ACCOUNT_KEY_SUCCESS = "ACCOUNT_KEY_SUCCESS";
export const ACCOUNT_KEY_FAIL = "ACCOUNT_KEY_FAIL";
export const RESET_ACCOUNT = "RESET_ACCOUNT";

export const LOAD_NFT_START = "LOAD_NFT_START";
export const NFT_LIST_SUCCESS = "NFT_LIST_SUCCESS";
export const NFT_LIST_FAIL = "NFT_LIST_FAIL";
export const NFT_LIST_RESET = "NFT_LIST_RESET";
export const PAGE_CHANGE = "PAGE_CHANGE";

export const HANDLE_LIKE_DISLIKE = "HANDLE_LIKE_DISLIKE";

export const HANDLE_SCREEN_NAME = "HANDLE_SCREEN_NAME";

export const MY_NFT_LOAD_START = "MY_NFT_LOAD_START";
export const MY_NFT_LOAD_FAIL = "MY_NFT_LOAD_FAIL";
export const MY_NFT_LOAD_RESET = "MY_NFT_LOAD_RESET";
export const MY_PAGE_CHANGE = "MY_PAGE_CHANGE";
export const FAVORITE_PAGE_CHANGE = "FAVORITE_PAGE_CHANGE";

export const MY_NFT_LOAD_SUCCESS = "MY_NFT_LOAD_SUCCESS";
export const FAVORITE_NFT_SUCCESS = "FAVORITE_NFT_SUCCESS";

export const NEW_NFT_LOAD_START = "NEW_NFT_LOAD_START";
export const NEW_NFT_LOAD_SUCCESS = "NEW_NFT_LOAD_SUCCESS";
export const NEW_NFT_LOAD_FAIL = "NEW_NFT_LOAD_FAIL";
export const NEW_PAGE_CHANGE = "NEW_PAGE_CHANGE";
export const NEW_NFT_LIST_RESET = "NEW_NFT_LIST_RESET";

export const TWOD_NFT_START = "TWOD_NFT_START";
export const TWOD_NFT_SUCCESS = "TWOD_NFT_SUCCESS";
export const TWOD_NFT_FAIL = "TWOD_NFT_FAIL";
export const TWOD_PAGE_CHANGE = "TWOD_PAGE_CHANGE";
export const TWOD_NFT_LIST_RESET = "TWOD_NFT_LIST_RESET";

export const NFT_LIST_UPDATE = "NFT_LIST_UPDATE";
export const NEW_NFT_LIST_UPDATE = "NEW_NFT_LIST_UPDATE";
export const FAVORITE_LIST_UPDATE = "FAVORITE_LIST_UPDATE";
export const MYLIST_LIST_UPDATE = "MYLIST_LIST_UPDATE";
export const TWOD_LIST_UPDATE = "TWOD_LIST_UPDATE";
export const ALL_ARTIST_SUCCESS = 'ALL_ARTIST_SUCCESS';

export const MY_COLLECTION_LOAD_FAIL = "MY_COLLECTION_LOAD_FAIL";
export const MY_COLLECTION_LOAD_START = "MY_COLLECTION_LOAD_START";
export const MY_COLLECTION_LOAD_RESET = "MY_COLLECTION_LOAD_RESET";
export const MY_COLLECTION_LOAD_SUCCESS = "MY_COLLECTION_LOAD_SUCCESS";
export const MY_COLLECTION_PAGE_CHANGE = "MY_COLLECTION_PAGE_CHANGE";
export const MY_COLLECTION_LIST_UPDATE = "MY_COLLECTION_LIST_UPDATE";


//#region XANALIA types
export const AUTH_LOADING_START = "AUTH_LOADING_START";
export const AUTH_LOADING_END = "AUTH_LOADING_END";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const UPDATE_CREATE = "UPDATE_CREATE";

export const WALLET_LOADING_START = "WALLET_LOADING_START";
export const WALLET_LOADING_END = "WALLET_LOADING_END";

export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';

export const ADD_ETH_TRANSACTION = "ADD_ETH_TRANSACTION";
export const ADD_BNB_TRANSACTION = "ADD_BNB_TRANSACTION";
export const ADD_MATIC_TRANSACTION = "ADD_MATIC_TRANSACTION";

export const ADD_ALL_ETH_TRANSACTIONS = "ADD_ALL_ETH_TRANSACTIONS";
export const ADD_ALL_BNB_TRANSACTIONS = "ADD_ALL_BNB_TRANSACTIONS";
export const ADD_ALL_MATIC_TRANSACTIONS = "ADD_ALL_MATIC_TRANSACTIONS";

export const UPDATE_BALANCES = "UPDATE_BALANCES";

    //#region Language action Types
    export const GET_EN_LANGUAGE_REQUEST = 'GET_EN_LANGUAGE_REQUEST';
    export const GET_EN_LANGUAGE_SUCCESS = 'GET_EN_LANGUAGE_SUCCESS';
    export const GET_EN_LANGUAGE_FAIL = 'GET_EN_LANGUAGE_FAIL';

    export const SET_LANGUAGE_SELECTED = 'SET_LANGUAGE_SELECTED';
    export const SET_ENGLISH_LANGUAGE = 'SET_ENGLISH_LANGUAGE';
    export const SET_JAPAN_LANGUAGE = 'SET_JAPAN_LANGUAGE';
    export const SET_KOREA_LANGUAGE = 'SET_KOREA_LANGUAGE';
    export const SET_CHINA_LANGUAGE = 'SET_CHINA_LANGUAGE';
    export const SET_TAIWAN_LANGUAGE = 'SET_TAIWAN_LANGUAGE';

    export const SET_ENGLISH_LANGUAGE_BACKEND = 'SET_ENGLISH_LANGUAGE_BACKEND';
    export const SET_JAPAN_LANGUAGE_BACKEND = 'SET_JAPAN_LANGUAGE_BACKEND';
    export const SET_KOREA_LANGUAGE_BACKEND = 'SET_KOREA_LANGUAGE_BACKEND';
    export const SET_CHINA_LANGUAGE_BACKEND = 'SET_CHINA_LANGUAGE_BACKEND';
    export const SET_TAIWAN_LANGUAGE_BACKEND = 'SET_TAIWAN_LANGUAGE_BACKEND';
    //#endregion

//#endregion