import {Platform, StyleSheet} from 'react-native';
import {hp, RF, wp} from '../../constants/responsiveFunct';
import Colors from '../../constants/Colors';
import CommonStyles from '../../constants/styles';
import {SIZE} from '../../common/responsiveFunction';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  chatContainer: {
    flex: 1,
    height: '100%',
    width: '100%',
    // flexGrow: 1,
  },
  inputContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: SIZE(5),
    marginHorizontal: SIZE(10),
    alignSelf: 'center',
  },
  input: message => ({
    paddingHorizontal: 15,
    height: hp(5),
    borderColor: '#ced4da',
    borderWidth: 2,
    width: message ? wp(85) : wp(65),
    borderRightColor: message ? '#ced4da' : '#3c7bde',
    borderRightWidth: message ? 2 : 0,
  }),
  sendBtn: disabled => ({
    paddingHorizontal: 15,
    height: hp(5),
    backgroundColor: '#3c7bde',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#3c7bde',
    borderWidth: 2,
    borderBottomRightRadius: 3,
    borderTopRightRadius: 3,
    opacity: disabled ? 0.5 : 1,
  }),
  sendText: {
    fontSize: 30,
    color: 'black',
  },
  talkBubble: ownerTittle => ({
    justifyContent: 'flex-end',
    maxWidth: ownerTittle ? '72%' : '80%',
  }),
  chatingTime: {
    color: '#888',
    fontSize: 10,
    fontWeight: '500',
  },
  icon: {
    ...CommonStyles.imageStyles(5),
  },
  timeView: {
    marginHorizontal: '2.5%',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  chatView: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 10,
    minHeight: 50,
    borderRadius: 5,
    backgroundColor: '#ebecf0',
  },
  scrollContent: {
    flexGrow: 1,
  },
  keyboardShift: {
    flex: 1,
  },
  bubbleContainer: type => ({
    alignItems: type === 'sender' ? 'flex-end' : 'flex-start',
    justifyContent: type === 'sender' ? 'flex-end' : 'flex-start',
    flexDirection: 'row',
  }),
  leftBubbleContainer: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    flexDirection: 'row',
  },
  isLoading: {
    ...CommonStyles.imageStyles(6),
    flex: 1,
    justifyContent: 'center',
  },
  searchBar: {
    borderWidth: 1,
    borderColor: '#e0e1e3',
    width: wp('95%'),
    height: hp('5%'),
    marginHorizontal: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    shadowColor: '#fff',
  },
  searchInputStyle: {
    fontSize: 14,
    color: Colors.BLACK1,
    height: '100%',
    margin: 0,
    padding: 0,
  },
  sorryMessageCont: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },
  sorryMessage: {
    fontSize: 15,
    fontWeight: '500',
  },
  backIcon: {
    width: SIZE(16),
    height: SIZE(16),
    resizeMode: 'contain',
  },
  backBtnContainer: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingHorizontal: SIZE(10),
    paddingRight: SIZE(12),
    position: 'absolute',
    top: 10,
    width: '100%',
  },
  backButtonWrap: {
    // left: SIZE(10),
    // paddingVertical: SIZE(12),
    // backgroundColor: 'white',
    backgroundColor: '#0D1216',
    width: SIZE(28),
    height: SIZE(28),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: SIZE(14),
  },
  imageViewWrap: {
    backgroundColor: '#EBECF0',
    padding: 5,
    borderRadius: 5,
  },
  separator: {
    width: wp('100%'),
    borderBottomColor: '#ced4da',
    borderBottomWidth: 2,
  },
  bubbleImage: {
    height: SIZE(40),
    width: SIZE(40),
    borderRadius: SIZE(40) / SIZE(2),
    marginBottom: 5,
  },
  bubbleText: {
    color: Colors.black,
    fontSize: 14,
  },
  hyperLinkText: {
    color: '#3c7bde',
    textTransform: 'lowercase',
    textDecorationLine: 'underline',
    fontStyle: 'italic',
  },
  chatHeaderContainer: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    paddingVertical: 5,
    marginLeft: 10,
  },
  cImageContainer: {
    height: 40,
    width: 40,
    borderRadius: 40 / 2,
  },
  headerNftName: {
    color: '#46446e',
    fontWeight: '700',
  },
  typingMessage: {
    color: '#888',
    fontWeight: 'bold',
    fontStyle: 'italic',
    fontSize: 11,
    paddingTop: 5,
  },
  remainWordText: {
    fontSize: 11,
    fontStyle: 'italic',
    paddingTop: 5,
    textAlign: 'right',
    fontWeight: 'bold',
    fontStyle: 'normal',
    alignSelf: 'flex-end',
  },
  sendBtnTxt: {
    color: '#fff',
    fontWeight: 'bold',
  },
  nftName: {
    color: '#fff',
    fontWeight: 'bold',
  },
  chatAuthorName: {
    fontWeight: '700',
    color: '#46446e',
    marginBottom: 5,
  },
  bannerImage: {
    width: '80%',
    height: '81%',
    resizeMode: 'contain',
  },
  bannerImgContainer: {
    // width: '100%',
    // height: '100%',
    // alignItems: 'center',
    // padding: 0,
    flex: 1,
    alignItems: 'center',
  },
  rcvReplyContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: '#3b3b3b',
    bottom: 0,
    position: 'absolute',
    zIndex: 2,
    width: wp(95),
    alignSelf: 'center',
    borderTopStartRadius: 12,
    borderTopEndRadius: 12,
  },
  nftItemContainer: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    paddingVertical: 5,
  },
  nftTextShow: {
    paddingVertical: 10,
    paddingStart: 10,
    marginLeft: 10,
    color: '#484848',
    fontWeight: '700',
  },
  centerViewStyle: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tabbar: {
    elevation: 0,
    borderTopColor: '#EFEFEF',
    borderTopWidth: 1,
    shadowOpacity: 0,
    backgroundColor: 'white',
    marginVertical: 10,
    width: wp(100),
  },
  label: {
    fontSize: RF(1.6),
    fontFamily: 'Arial',
    textTransform: 'none',
  },
  tabStyle: {
    height: SIZE(40),
    width: wp(100) / 3,
    paddingHorizontal: wp('1%'),
    justifyContent: 'center',
  },
  indicator: {
    borderBottomColor: Colors.BLUE4,
    height: 1,
    marginBottom: SIZE(39),
    backgroundColor: Colors.BLUE4,
  },
  mainListContainer: {
    backgroundColor: Colors.white,
    flex: 1,
  },
  nftListContainer: {
    flex: 1,
    padding: 10,
  },
  typingContainer: {
    flexDirection: 'row',
    flex: 0.5,
  },
  rcvContainerArrow: {
    borderLeftWidth: 25,
    borderRightWidth: 25,
    borderBottomWidth: 70,
    backgroundColor: 'transparent',
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#3b3b3b',
    top: -35,
    position: 'absolute',
    left: 25,
    transform: [{rotate: '36deg'}],
  },
  editButtonView: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginRight: 15,
  },
  cancelButton: {
    backgroundColor: '#ebecf0',
    marginRight: 10,
    borderWidth: 0,
    borderRadius: 5,
    borderBottomRightRadius: 5,
    borderTopRightRadius: 5,
    height: hp(5),
  },
  cancelLabel: {
    color: 'black',
    fontWeight: 'normal',
  },
  saveButton: {
    borderRadius: 5,
    borderBottomRightRadius: 6,
    borderTopRightRadius: 5,
  },
  threeDotView: {
    alignSelf: 'center',
    backgroundColor: '#ebecf0',
    borderRadius: 90,
    padding: 4,
    marginLeft: 10,
  },
  editPopupContainer: {
    marginTop: SIZE(25),
    width: wp(15),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: 'white',
    borderWidth: 0.5,
    borderColor: '#ebecf0',
  },
  mainView: {
    paddingStart: 10,
    flexDirection: 'column',
    width: '86%',
  },
  remainWordCountView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  micContainer: {
    backgroundColor: '#3c7bde',
    width: SIZE(40),
    height: SIZE(40),
    borderRadius: SIZE(40 / 2),
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: SIZE(5),
  },
});

export default styles;
