import { networkType } from "../../networkType.js";

let abi = "";
if (networkType === "testnet") {
  abi = [
    {
      type: "function",
      stateMutability: "view",
      payable: false,
      outputs: [{ type: "string", name: "" }],
      name: "name",
      inputs: [],
      constant: true,
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      payable: false,
      outputs: [{ type: "bool", name: "" }],
      name: "approve",
      inputs: [
        { type: "address", name: "spender" },
        { type: "uint256", name: "value" },
      ],
      constant: false,
    },
    {
      type: "function",
      stateMutability: "view",
      payable: false,
      outputs: [{ type: "uint256", name: "" }],
      name: "totalSupply",
      inputs: [],
      constant: true,
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      payable: false,
      outputs: [{ type: "bool", name: "" }],
      name: "transferFrom",
      inputs: [
        { type: "address", name: "from" },
        { type: "address", name: "to" },
        { type: "uint256", name: "value" },
      ],
      constant: false,
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      payable: false,
      outputs: [],
      name: "addBlackListAddress",
      inputs: [{ type: "address", name: "addressToBlock" }],
      constant: false,
    },
    {
      type: "function",
      stateMutability: "view",
      payable: false,
      outputs: [{ type: "uint8", name: "" }],
      name: "decimals",
      inputs: [],
      constant: true,
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      payable: false,
      outputs: [{ type: "bool", name: "" }],
      name: "increaseAllowance",
      inputs: [
        { type: "address", name: "spender" },
        { type: "uint256", name: "addedValue" },
      ],
      constant: false,
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      payable: false,
      outputs: [],
      name: "unpause",
      inputs: [],
      constant: false,
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      payable: false,
      outputs: [{ type: "bool", name: "" }],
      name: "mint",
      inputs: [
        { type: "address", name: "to" },
        { type: "uint256", name: "value" },
      ],
      constant: false,
    },
    {
      type: "function",
      stateMutability: "view",
      payable: false,
      outputs: [{ type: "bool", name: "" }],
      name: "isPauser",
      inputs: [{ type: "address", name: "account" }],
      constant: true,
    },
    {
      type: "function",
      stateMutability: "view",
      payable: false,
      outputs: [{ type: "bool", name: "" }],
      name: "isBlackListAddress",
      inputs: [{ type: "address", name: "addressToCheck" }],
      constant: true,
    },
    {
      type: "function",
      stateMutability: "view",
      payable: false,
      outputs: [{ type: "bool", name: "" }],
      name: "paused",
      inputs: [],
      constant: true,
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      payable: false,
      outputs: [],
      name: "renouncePauser",
      inputs: [],
      constant: false,
    },
    {
      type: "function",
      stateMutability: "view",
      payable: false,
      outputs: [{ type: "uint256", name: "" }],
      name: "balanceOf",
      inputs: [{ type: "address", name: "owner" }],
      constant: true,
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      payable: false,
      outputs: [],
      name: "renounceOwnership",
      inputs: [],
      constant: false,
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      payable: false,
      outputs: [],
      name: "addPauser",
      inputs: [{ type: "address", name: "account" }],
      constant: false,
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      payable: false,
      outputs: [],
      name: "pause",
      inputs: [],
      constant: false,
    },
    {
      type: "function",
      stateMutability: "view",
      payable: false,
      outputs: [{ type: "address", name: "" }],
      name: "owner",
      inputs: [],
      constant: true,
    },
    {
      type: "function",
      stateMutability: "view",
      payable: false,
      outputs: [{ type: "string", name: "" }],
      name: "symbol",
      inputs: [],
      constant: true,
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      payable: false,
      outputs: [],
      name: "addMinter",
      inputs: [{ type: "address", name: "account" }],
      constant: false,
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      payable: false,
      outputs: [],
      name: "renounceMinter",
      inputs: [],
      constant: false,
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      payable: false,
      outputs: [],
      name: "burn",
      inputs: [
        { type: "address", name: "account" },
        { type: "uint256", name: "value" },
      ],
      constant: false,
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      payable: false,
      outputs: [{ type: "bool", name: "" }],
      name: "decreaseAllowance",
      inputs: [
        { type: "address", name: "spender" },
        { type: "uint256", name: "subtractedValue" },
      ],
      constant: false,
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      payable: false,
      outputs: [{ type: "bool", name: "" }],
      name: "transfer",
      inputs: [
        { type: "address", name: "to" },
        { type: "uint256", name: "value" },
      ],
      constant: false,
    },
    {
      type: "function",
      stateMutability: "view",
      payable: false,
      outputs: [{ type: "bool", name: "" }],
      name: "isMinter",
      inputs: [{ type: "address", name: "account" }],
      constant: true,
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      payable: false,
      outputs: [],
      name: "removeBlackListAddress",
      inputs: [{ type: "address", name: "addressToRemove" }],
      constant: false,
    },
    {
      type: "function",
      stateMutability: "view",
      payable: false,
      outputs: [{ type: "uint256", name: "" }],
      name: "allowance",
      inputs: [
        { type: "address", name: "owner" },
        { type: "address", name: "spender" },
      ],
      constant: true,
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      payable: false,
      outputs: [],
      name: "init",
      inputs: [],
      constant: false,
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      payable: false,
      outputs: [],
      name: "transferOwnership",
      inputs: [{ type: "address", name: "newOwner" }],
      constant: false,
    },
    {
      type: "constructor",
      stateMutability: "nonpayable",
      payable: false,
      inputs: [],
    },
    {
      type: "event",
      name: "Paused",
      inputs: [{ type: "address", name: "account", indexed: false }],
      anonymous: false,
    },
    {
      type: "event",
      name: "Unpaused",
      inputs: [{ type: "address", name: "account", indexed: false }],
      anonymous: false,
    },
    {
      type: "event",
      name: "PauserAdded",
      inputs: [{ type: "address", name: "account", indexed: true }],
      anonymous: false,
    },
    {
      type: "event",
      name: "PauserRemoved",
      inputs: [{ type: "address", name: "account", indexed: true }],
      anonymous: false,
    },
    {
      type: "event",
      name: "MinterAdded",
      inputs: [{ type: "address", name: "account", indexed: true }],
      anonymous: false,
    },
    {
      type: "event",
      name: "MinterRemoved",
      inputs: [{ type: "address", name: "account", indexed: true }],
      anonymous: false,
    },
    {
      type: "event",
      name: "OwnershipTransferred",
      inputs: [
        { type: "address", name: "previousOwner", indexed: true },
        { type: "address", name: "newOwner", indexed: true },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Transfer",
      inputs: [
        { type: "address", name: "from", indexed: true },
        { type: "address", name: "to", indexed: true },
        { type: "uint256", name: "value", indexed: false },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Approval",
      inputs: [
        { type: "address", name: "owner", indexed: true },
        { type: "address", name: "spender", indexed: true },
        { type: "uint256", name: "value", indexed: false },
      ],
      anonymous: false,
    },
  ];
} else if (networkType === "mainnet") {
  abi = [
    {
      constant: true,
      inputs: [],
      name: "name",
      outputs: [{ name: "", type: "string" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "spender", type: "address" },
        { name: "value", type: "uint256" },
      ],
      name: "approve",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "totalSupply",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "from", type: "address" },
        { name: "to", type: "address" },
        { name: "value", type: "uint256" },
      ],
      name: "transferFrom",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "addressToBlock", type: "address" }],
      name: "addBlackListAddress",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "decimals",
      outputs: [{ name: "", type: "uint8" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "spender", type: "address" },
        { name: "addedValue", type: "uint256" },
      ],
      name: "increaseAllowance",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "unpause",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "to", type: "address" },
        { name: "value", type: "uint256" },
      ],
      name: "mint",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "account", type: "address" }],
      name: "isPauser",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "addressToCheck", type: "address" }],
      name: "isBlackListAddress",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "paused",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "renouncePauser",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "owner", type: "address" }],
      name: "balanceOf",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "renounceOwnership",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "account", type: "address" }],
      name: "addPauser",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "pause",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "owner",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "symbol",
      outputs: [{ name: "", type: "string" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "account", type: "address" }],
      name: "addMinter",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "renounceMinter",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "account", type: "address" },
        { name: "value", type: "uint256" },
      ],
      name: "burn",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "spender", type: "address" },
        { name: "subtractedValue", type: "uint256" },
      ],
      name: "decreaseAllowance",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "to", type: "address" },
        { name: "value", type: "uint256" },
      ],
      name: "transfer",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "account", type: "address" }],
      name: "isMinter",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "addressToRemove", type: "address" }],
      name: "removeBlackListAddress",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "owner", type: "address" },
        { name: "spender", type: "address" },
      ],
      name: "allowance",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "init",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "newOwner", type: "address" }],
      name: "transferOwnership",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, name: "account", type: "address" }],
      name: "Paused",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, name: "account", type: "address" }],
      name: "Unpaused",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, name: "account", type: "address" }],
      name: "PauserAdded",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, name: "account", type: "address" }],
      name: "PauserRemoved",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, name: "account", type: "address" }],
      name: "MinterAdded",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, name: "account", type: "address" }],
      name: "MinterRemoved",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "previousOwner", type: "address" },
        { indexed: true, name: "newOwner", type: "address" },
      ],
      name: "OwnershipTransferred",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: true, name: "to", type: "address" },
        { indexed: false, name: "value", type: "uint256" },
      ],
      name: "Transfer",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "owner", type: "address" },
        { indexed: true, name: "spender", type: "address" },
        { indexed: false, name: "value", type: "uint256" },
      ],
      name: "Approval",
      type: "event",
    },
  ];
}
export default abi;
