import { networkType } from "../../networkType.js";

let abi = "";
if (networkType === "testnet") {
  abi = [
    {
      constant: false,
      inputs: [],
      name: "init2",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "artistId", type: "string" },
        { name: "tokenId", type: "uint256" },
        { name: "_isArtist", type: "bool" },
      ],
      name: "addNonCryptoAuthor",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "title", type: "string" },
        { name: "description", type: "string" },
        { name: "image", type: "string" },
        { name: "price", type: "uint256" },
        { name: "usdPrice", type: "uint256" },
        { name: "countNFT", type: "uint256" },
        { name: "detailHash", type: "string" },
      ],
      name: "createCategory",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "getNonCryptoAuthor",
      outputs: [{ name: "", type: "string" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "_artistPercentage", type: "uint256" },
        { name: "_companyPercentage", type: "uint256" },
        { name: "artistId", type: "string" },
      ],
      name: "updateCompanyPercentage",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "buyer", type: "address" },
        { name: "price", type: "uint256" },
        { name: "nftVaultAddress", type: "address" },
        { name: "tokenId", type: "uint256" },
        { name: "platform", type: "address" },
        { name: "platformPerecentage", type: "uint256" },
      ],
      name: "transferAliaArtist",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "init3",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "name", type: "string" }],
      name: "getBoxDetail",
      outputs: [
        { name: "", type: "string" },
        { name: "", type: "string" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "index", type: "uint256" },
        { name: "artistId", type: "string" },
      ],
      name: "removeAgent",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "artistId", type: "string" }],
      name: "getPercentagesAndCount",
      outputs: [
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "index", type: "uint256" },
        { name: "artistId", type: "string" },
      ],
      name: "getAgent",
      outputs: [
        { name: "", type: "string" },
        { name: "", type: "address" },
        { name: "", type: "uint256" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "uris", type: "string" },
      ],
      name: "addUriToCategory",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "artistId", type: "string" },
        { name: "tokenId", type: "uint256" },
      ],
      name: "checkArtistOwner",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "artistId", type: "string" }],
      name: "allArtistAgentPercentages",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "checkTokenAuthorIsArtist",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "seller", type: "address" },
        { name: "ownerId", type: "string" },
        { name: "name", type: "string" },
      ],
      name: "buyBox",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "index", type: "uint256" },
        { name: "agentId", type: "string" },
        { name: "_agentAddress", type: "address" },
        { name: "artistId", type: "string" },
        { name: "_percentage", type: "uint256" },
        { name: "_artistPercentage", type: "uint256" },
      ],
      name: "editAgent",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "priceDollar", type: "uint256" }],
      name: "calculatePriceUSDToAlia",
      outputs: [{ name: "price", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "init1",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "title", type: "string" },
        { name: "description", type: "string" },
        { name: "image", type: "string" },
        { name: "price", type: "uint256" },
        { name: "usdPrice", type: "uint256" },
        { name: "count", type: "uint256" },
        { name: "detailHash", type: "string" },
      ],
      name: "updateAllValueOfPack",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "agentId", type: "string" },
        { name: "_agentAddress", type: "address" },
        { name: "artistId", type: "string" },
        { name: "_percentage", type: "uint256" },
        { name: "_artistPercentage", type: "uint256" },
      ],
      name: "addAgent",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "title", type: "string" },
        { indexed: false, name: "description", type: "string" },
        { indexed: false, name: "image", type: "string" },
        { indexed: false, name: "price", type: "uint256" },
        { indexed: false, name: "usdPrice", type: "uint256" },
        { indexed: false, name: "countNFT", type: "uint256" },
        { indexed: false, name: "detailHash", type: "string" },
      ],
      name: "CreateCategory",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "uri", type: "string" },
        { indexed: false, name: "count", type: "uint256" },
      ],
      name: "URIAdded",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "buyer", type: "address" },
        { indexed: false, name: "ownerId", type: "string" },
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "tokenIds", type: "uint256" },
      ],
      name: "BuyBox",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "title", type: "string" },
        { indexed: false, name: "description", type: "string" },
        { indexed: false, name: "image", type: "string" },
        { indexed: false, name: "price", type: "uint256" },
        { indexed: false, name: "usdPrice", type: "uint256" },
        { indexed: false, name: "count", type: "uint256" },
        { indexed: false, name: "detailHash", type: "string" },
      ],
      name: "UpdateAllValueOfPack",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "index", type: "uint256" },
        { indexed: false, name: "agentId", type: "string" },
        { indexed: false, name: "_agentAddress", type: "address" },
        { indexed: false, name: "artistId", type: "string" },
        { indexed: false, name: "_percentage", type: "uint256" },
        { indexed: false, name: "_artistPercentage", type: "uint256" },
      ],
      name: "AddAgent",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "index", type: "uint256" },
        { indexed: false, name: "agentId", type: "string" },
        { indexed: false, name: "_agentAddress", type: "address" },
        { indexed: false, name: "artistId", type: "string" },
        { indexed: false, name: "_percentage", type: "uint256" },
        { indexed: false, name: "_artistPercentage", type: "uint256" },
      ],
      name: "EditAgent",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "index", type: "uint256" },
        { indexed: false, name: "artistId", type: "string" },
      ],
      name: "RemoveAgent",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "_artistPercentage", type: "uint256" },
        { indexed: false, name: "_companyPercentage", type: "uint256" },
        { indexed: false, name: "artistId", type: "string" },
      ],
      name: "UpdateCompanyPercentage",
      type: "event",
    },
  ];
} else {
  abi = [
    {
      constant: false,
      inputs: [],
      name: "init2",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "title", type: "string" },
        { name: "description", type: "string" },
        { name: "image", type: "string" },
        { name: "price", type: "uint256" },
        { name: "usdPrice", type: "uint256" },
        { name: "countNFT", type: "uint256" },
        { name: "detailHash", type: "string" },
      ],
      name: "createCategory",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "name", type: "string" }],
      name: "getBoxDetail",
      outputs: [
        { name: "", type: "string" },
        { name: "", type: "string" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "uris", type: "string" },
      ],
      name: "addUriToCategory",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "seller", type: "address" },
        { name: "ownerId", type: "string" },
        { name: "name", type: "string" },
      ],
      name: "buyBox",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "init1",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "title", type: "string" },
        { name: "description", type: "string" },
        { name: "image", type: "string" },
        { name: "price", type: "uint256" },
        { name: "usdPrice", type: "uint256" },
        { name: "count", type: "uint256" },
        { name: "detailHash", type: "string" },
      ],
      name: "updateAllValueOfPack",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "title", type: "string" },
        { indexed: false, name: "description", type: "string" },
        { indexed: false, name: "image", type: "string" },
        { indexed: false, name: "price", type: "uint256" },
        { indexed: false, name: "usdPrice", type: "uint256" },
        { indexed: false, name: "countNFT", type: "uint256" },
        { indexed: false, name: "detailHash", type: "string" },
      ],
      name: "CreateCategory",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "uri", type: "string" },
        { indexed: false, name: "count", type: "uint256" },
      ],
      name: "URIAdded",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "buyer", type: "address" },
        { indexed: false, name: "ownerId", type: "string" },
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "tokenIds", type: "uint256" },
      ],
      name: "BuyBox",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "title", type: "string" },
        { indexed: false, name: "description", type: "string" },
        { indexed: false, name: "image", type: "string" },
        { indexed: false, name: "price", type: "uint256" },
        { indexed: false, name: "usdPrice", type: "uint256" },
        { indexed: false, name: "count", type: "uint256" },
        { indexed: false, name: "detailHash", type: "string" },
      ],
      name: "UpdateAllValueOfPack",
      type: "event",
    },
  ];
}

export default abi;
