import { networkType } from "../../networkType.js";

let abi = "";
if (networkType === "testnet") {
  abi = [
    {
      constant: true,
      inputs: [{ name: "name", type: "string" }],
      name: "getBoxDetail",
      outputs: [
        { name: "", type: "string" },
        { name: "", type: "string" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "uris", type: "string" },
      ],
      name: "addUriToCategory",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "title", type: "string" },
        { name: "description", type: "string" },
        { name: "image", type: "string" },
        { name: "price", type: "uint256" },
        { name: "usdPrice", type: "uint256" },
        { name: "count", type: "uint256" },
      ],
      name: "updateAllValueOfPack",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "seller", type: "address" },
        { name: "ownerId", type: "string" },
        { name: "name", type: "string" },
      ],
      name: "buyBox",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "title", type: "string" },
        { name: "description", type: "string" },
        { name: "image", type: "string" },
        { name: "price", type: "uint256" },
        { name: "usdPrice", type: "uint256" },
        { name: "countNFT", type: "uint256" },
      ],
      name: "createCategory",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "init1",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "title", type: "string" },
        { indexed: false, name: "description", type: "string" },
        { indexed: false, name: "image", type: "string" },
        { indexed: false, name: "price", type: "uint256" },
        { indexed: false, name: "usdPrice", type: "uint256" },
        { indexed: false, name: "countNFT", type: "uint256" },
      ],
      name: "CreateCategory",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "uri", type: "string" },
        { indexed: false, name: "count", type: "uint256" },
      ],
      name: "URIAdded",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "buyer", type: "address" },
        { indexed: false, name: "ownerId", type: "string" },
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "tokenIds", type: "uint256" },
      ],
      name: "BuyBox",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "title", type: "string" },
        { indexed: false, name: "description", type: "string" },
        { indexed: false, name: "image", type: "string" },
        { indexed: false, name: "price", type: "uint256" },
        { indexed: false, name: "usdPrice", type: "uint256" },
        { indexed: false, name: "count", type: "uint256" },
      ],
      name: "UpdateAllValueOfPack",
      type: "event",
    },
  ];
} else {
  abi = [
    {
      constant: false,
      inputs: [],
      name: "init2",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "title", type: "string" },
        { name: "description", type: "string" },
        { name: "image", type: "string" },
        { name: "price", type: "uint256" },
        { name: "usdPrice", type: "uint256" },
        { name: "countNFT", type: "uint256" },
        { name: "detailHash", type: "string" },
      ],
      name: "createCategory",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "name", type: "string" }],
      name: "getBoxDetail",
      outputs: [
        { name: "", type: "string" },
        { name: "", type: "string" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "uris", type: "string" },
      ],
      name: "addUriToCategory",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "seller", type: "address" },
        { name: "ownerId", type: "string" },
        { name: "name", type: "string" },
      ],
      name: "buyBox",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "init1",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "title", type: "string" },
        { name: "description", type: "string" },
        { name: "image", type: "string" },
        { name: "price", type: "uint256" },
        { name: "usdPrice", type: "uint256" },
        { name: "count", type: "uint256" },
        { name: "detailHash", type: "string" },
      ],
      name: "updateAllValueOfPack",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "title", type: "string" },
        { indexed: false, name: "description", type: "string" },
        { indexed: false, name: "image", type: "string" },
        { indexed: false, name: "price", type: "uint256" },
        { indexed: false, name: "usdPrice", type: "uint256" },
        { indexed: false, name: "countNFT", type: "uint256" },
        { indexed: false, name: "detailHash", type: "string" },
      ],
      name: "CreateCategory",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "uri", type: "string" },
        { indexed: false, name: "count", type: "uint256" },
      ],
      name: "URIAdded",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "buyer", type: "address" },
        { indexed: false, name: "ownerId", type: "string" },
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "tokenIds", type: "uint256" },
      ],
      name: "BuyBox",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "title", type: "string" },
        { indexed: false, name: "description", type: "string" },
        { indexed: false, name: "image", type: "string" },
        { indexed: false, name: "price", type: "uint256" },
        { indexed: false, name: "usdPrice", type: "uint256" },
        { indexed: false, name: "count", type: "uint256" },
        { indexed: false, name: "detailHash", type: "string" },
      ],
      name: "UpdateAllValueOfPack",
      type: "event",
    },
  ];
}

export default abi;
