import { networkType } from "../../networkType.js";

let abi = "";
if (networkType === "testnet") {
  abi = [
    {
      constant: true,
      inputs: [{ name: "name", type: "string" }],
      name: "isSellable",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "name", type: "string" },
        { name: "selectedTime", type: "uint256" },
      ],
      name: "getBoxDetail",
      outputs: [
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
        { name: "", type: "bool" },
        { name: "", type: "uint256" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "_time", type: "uint256" },
      ],
      name: "initializeBox",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "init3",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "selectedTime", type: "uint256" },
        { name: "name", type: "string" },
      ],
      name: "isBoxSold",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "uris", type: "string" },
      ],
      name: "addUriToCategory",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "name", type: "string" },
        { name: "selectedTime", type: "uint256" },
      ],
      name: "getBoxDetailsNonCrypto",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "startingIndex", type: "uint256" },
      ],
      name: "initializeBox4",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "title", type: "string" },
        { name: "description", type: "string" },
        { name: "image", type: "string" },
        { name: "price", type: "uint256" },
        { name: "usdPrice", type: "uint256" },
        { name: "countNFT", type: "uint256" },
        { name: "detailHash", type: "string" },
        { name: "_address", type: "address" },
      ],
      name: "createCategory",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "seller", type: "address" },
        { name: "to", type: "address" },
        { name: "ownerId", type: "string" },
        { name: "name", type: "string" },
      ],
      name: "buyBoxAdmin",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "index", type: "uint256" },
      ],
      name: "removeTokenUri",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "seller", type: "address" },
        { name: "ownerId", type: "string" },
        { name: "name", type: "string" },
        { name: "selectedTime", type: "uint256" },
        { name: "isPaid", type: "bool" },
      ],
      name: "buyBox",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "init1",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "_address", type: "address" },
      ],
      name: "updateRevenue",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "title", type: "string" },
        { name: "description", type: "string" },
        { name: "image", type: "string" },
        { name: "price", type: "uint256" },
        { name: "usdPrice", type: "uint256" },
        { name: "count", type: "uint256" },
        { name: "detailHash", type: "string" },
      ],
      name: "updateAllValueOfPack",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "title", type: "string" },
        { indexed: false, name: "description", type: "string" },
        { indexed: false, name: "image", type: "string" },
        { indexed: false, name: "price", type: "uint256" },
        { indexed: false, name: "usdPrice", type: "uint256" },
        { indexed: false, name: "countNFT", type: "uint256" },
        { indexed: false, name: "detailHash", type: "string" },
        { indexed: false, name: "revenueAddress", type: "address" },
      ],
      name: "CreateCategory",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "uri", type: "string" },
        { indexed: false, name: "count", type: "uint256" },
      ],
      name: "URIAdded",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "buyer", type: "address" },
        { indexed: false, name: "ownerId", type: "string" },
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "tokenIds", type: "uint256" },
      ],
      name: "BuyBox",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "title", type: "string" },
        { indexed: false, name: "description", type: "string" },
        { indexed: false, name: "image", type: "string" },
        { indexed: false, name: "price", type: "uint256" },
        { indexed: false, name: "usdPrice", type: "uint256" },
        { indexed: false, name: "count", type: "uint256" },
        { indexed: false, name: "detailHash", type: "string" },
      ],
      name: "UpdateAllValueOfPack",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "index", type: "uint256" },
        { indexed: false, name: "agentId", type: "string" },
        { indexed: false, name: "_agentAddress", type: "address" },
        { indexed: false, name: "artistId", type: "string" },
        { indexed: false, name: "_percentage", type: "uint256" },
        { indexed: false, name: "_artistPercentage", type: "uint256" },
      ],
      name: "AddAgent",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "index", type: "uint256" },
        { indexed: false, name: "agentId", type: "string" },
        { indexed: false, name: "_agentAddress", type: "address" },
        { indexed: false, name: "artistId", type: "string" },
        { indexed: false, name: "_percentage", type: "uint256" },
        { indexed: false, name: "_artistPercentage", type: "uint256" },
      ],
      name: "EditAgent",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "index", type: "uint256" },
        { indexed: false, name: "artistId", type: "string" },
      ],
      name: "RemoveAgent",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "_artistPercentage", type: "uint256" },
        { indexed: false, name: "_companyPercentage", type: "uint256" },
        { indexed: false, name: "artistId", type: "string" },
      ],
      name: "UpdateCompanyPercentage",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "tokenUri", type: "string" },
        { indexed: false, name: "index", type: "uint256" },
      ],
      name: "TokenUriUsed",
      type: "event",
    },
  ];
} else {
  abi = [
    {
      constant: true,
      inputs: [{ name: "name", type: "string" }],
      name: "isSellable",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "name", type: "string" },
        { name: "selectedTime", type: "uint256" },
      ],
      name: "getBoxDetail",
      outputs: [
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
        { name: "", type: "bool" },
        { name: "", type: "uint256" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "_time", type: "uint256" },
      ],
      name: "initializeBox",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "init3",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "selectedTime", type: "uint256" },
        { name: "name", type: "string" },
      ],
      name: "isBoxSold",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "uris", type: "string" },
      ],
      name: "addUriToCategory",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "name", type: "string" },
        { name: "selectedTime", type: "uint256" },
      ],
      name: "getBoxDetailsNonCrypto",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "startingIndex", type: "uint256" },
      ],
      name: "initializeBox4",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "title", type: "string" },
        { name: "description", type: "string" },
        { name: "image", type: "string" },
        { name: "price", type: "uint256" },
        { name: "usdPrice", type: "uint256" },
        { name: "countNFT", type: "uint256" },
        { name: "detailHash", type: "string" },
        { name: "_address", type: "address" },
      ],
      name: "createCategory",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "seller", type: "address" },
        { name: "to", type: "address" },
        { name: "ownerId", type: "string" },
        { name: "name", type: "string" },
      ],
      name: "buyBoxAdmin",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "index", type: "uint256" },
      ],
      name: "removeTokenUri",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "seller", type: "address" },
        { name: "ownerId", type: "string" },
        { name: "name", type: "string" },
        { name: "selectedTime", type: "uint256" },
        { name: "isPaid", type: "bool" },
      ],
      name: "buyBox",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "init1",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "_address", type: "address" },
      ],
      name: "updateRevenue",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "name", type: "string" },
        { name: "title", type: "string" },
        { name: "description", type: "string" },
        { name: "image", type: "string" },
        { name: "price", type: "uint256" },
        { name: "usdPrice", type: "uint256" },
        { name: "count", type: "uint256" },
        { name: "detailHash", type: "string" },
      ],
      name: "updateAllValueOfPack",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "title", type: "string" },
        { indexed: false, name: "description", type: "string" },
        { indexed: false, name: "image", type: "string" },
        { indexed: false, name: "price", type: "uint256" },
        { indexed: false, name: "usdPrice", type: "uint256" },
        { indexed: false, name: "countNFT", type: "uint256" },
        { indexed: false, name: "detailHash", type: "string" },
        { indexed: false, name: "revenueAddress", type: "address" },
      ],
      name: "CreateCategory",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "uri", type: "string" },
        { indexed: false, name: "count", type: "uint256" },
      ],
      name: "URIAdded",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "buyer", type: "address" },
        { indexed: false, name: "ownerId", type: "string" },
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "tokenIds", type: "uint256" },
      ],
      name: "BuyBox",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "title", type: "string" },
        { indexed: false, name: "description", type: "string" },
        { indexed: false, name: "image", type: "string" },
        { indexed: false, name: "price", type: "uint256" },
        { indexed: false, name: "usdPrice", type: "uint256" },
        { indexed: false, name: "count", type: "uint256" },
        { indexed: false, name: "detailHash", type: "string" },
      ],
      name: "UpdateAllValueOfPack",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "index", type: "uint256" },
        { indexed: false, name: "agentId", type: "string" },
        { indexed: false, name: "_agentAddress", type: "address" },
        { indexed: false, name: "artistId", type: "string" },
        { indexed: false, name: "_percentage", type: "uint256" },
        { indexed: false, name: "_artistPercentage", type: "uint256" },
      ],
      name: "AddAgent",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "index", type: "uint256" },
        { indexed: false, name: "agentId", type: "string" },
        { indexed: false, name: "_agentAddress", type: "address" },
        { indexed: false, name: "artistId", type: "string" },
        { indexed: false, name: "_percentage", type: "uint256" },
        { indexed: false, name: "_artistPercentage", type: "uint256" },
      ],
      name: "EditAgent",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "index", type: "uint256" },
        { indexed: false, name: "artistId", type: "string" },
      ],
      name: "RemoveAgent",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "_artistPercentage", type: "uint256" },
        { indexed: false, name: "_companyPercentage", type: "uint256" },
        { indexed: false, name: "artistId", type: "string" },
      ],
      name: "UpdateCompanyPercentage",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "name", type: "string" },
        { indexed: false, name: "tokenUri", type: "string" },
        { indexed: false, name: "index", type: "uint256" },
      ],
      name: "TokenUriUsed",
      type: "event",
    },
  ];
}

export default abi;
