import { networkType } from "../common/networkType.js";

let abi = "";
if (networkType === "testnet") {
  abi = [{ "constant": false, "inputs": [{ "name": "nft_a", "type": "address" }, { "name": "tokenId", "type": "uint256" }, { "name": "ownerId", "type": "string" }], "name": "buyNftNonCrypto", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [{ "name": "interfaceId", "type": "bytes4" }], "name": "supportsInterface", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [], "name": "name", "outputs": [{ "name": "", "type": "string" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "tokenId", "type": "uint256" }], "name": "cancelSell", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [{ "name": "tokenId", "type": "uint256" }], "name": "getApproved", "outputs": [{ "name": "", "type": "address" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "to", "type": "address" }, { "name": "tokenId", "type": "uint256" }], "name": "approve", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [{ "name": "owner", "type": "address" }, { "name": "tokenId", "type": "uint256" }], "name": "transferFromAdmin", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [{ "name": "tokenId", "type": "uint256" }, { "name": "newPrice", "type": "uint256" }, { "name": "newDollarPrice", "type": "uint256" }], "name": "updatePrice", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "totalSupply", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [{ "name": "", "type": "address" }], "name": "_supportNft", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "from", "type": "address" }, { "name": "to", "type": "address" }, { "name": "tokenId", "type": "uint256" }], "name": "transferFrom", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [{ "name": "_contract", "type": "address" }, { "name": "_tokenId", "type": "uint256" }, { "name": "_minPrice", "type": "uint256" }, { "name": "_endTime", "type": "uint256" }], "name": "setOnAuction", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [{ "name": "owner", "type": "address" }, { "name": "index", "type": "uint256" }], "name": "tokenOfOwnerByIndex", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "from", "type": "address" }, { "name": "to", "type": "address" }, { "name": "tokenId", "type": "uint256" }], "name": "safeTransferFrom", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [{ "name": "to", "type": "address" }, { "name": "tokenURI", "type": "string" }, { "name": "quantity", "type": "uint256" }, { "name": "flag", "type": "bool" }, { "name": "_contract", "type": "address" }, { "name": "_minPrice", "type": "uint256" }, { "name": "_endTime", "type": "uint256" }, { "name": "royality", "type": "uint256" }], "name": "MintAndAuctionNFT", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "platform", "outputs": [{ "name": "", "type": "address" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [{ "name": "index", "type": "uint256" }], "name": "tokenByIndex", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "_tokenId", "type": "uint256" }, { "name": "_amount", "type": "uint256" }], "name": "placeBid", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [{ "name": "token_addr", "type": "address" }, { "name": "_platform", "type": "address" }, { "name": "_authorVault", "type": "address" }, { "name": "_lp", "type": "address" }, { "name": "lpBnb", "type": "address" }], "name": "setAddresses", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [{ "name": "tokenId", "type": "uint256" }], "name": "ownerOf", "outputs": [{ "name": "", "type": "address" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [{ "name": "", "type": "uint256" }], "name": "_royality", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "to", "type": "address" }, { "name": "tokenURI", "type": "string" }, { "name": "quantity", "type": "uint256" }, { "name": "flag", "type": "bool" }], "name": "mintWithTokenURIE", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "allTokens", "outputs": [{ "name": "", "type": "uint256[]" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [{ "name": "owner", "type": "address" }], "name": "balanceOf", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [], "name": "renounceOwnership", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [{ "name": "owner", "type": "address" }, { "name": "tokenId", "type": "uint256" }, { "name": "price", "type": "uint256" }], "name": "listNftAdmin", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [{ "name": "tokenId", "type": "uint256" }], "name": "onAuctionOrNot", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [{ "name": "ownerId", "type": "string" }], "name": "getNonCryptoWallet", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [{ "name": "owner", "type": "address" }], "name": "tokensOfOwner", "outputs": [{ "name": "", "type": "uint256[]" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [], "name": "owner", "outputs": [{ "name": "", "type": "address" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [], "name": "isOwner", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [], "name": "symbol", "outputs": [{ "name": "", "type": "string" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "account", "type": "address" }], "name": "addMinter", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [], "name": "renounceMinter", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [{ "name": "_tokenId", "type": "uint256" }], "name": "claimAuction", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [{ "name": "tokenId", "type": "uint256" }], "name": "getSellDetail", "outputs": [{ "name": "", "type": "address" }, { "name": "", "type": "uint256" }, { "name": "", "type": "uint256" }, { "name": "", "type": "address" }, { "name": "", "type": "uint256" }, { "name": "", "type": "uint256" }, { "name": "", "type": "uint256" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [{ "name": "tokenIdFunction", "type": "uint256" }], "name": "getAuthor", "outputs": [{ "name": "", "type": "address" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "to", "type": "address" }, { "name": "approved", "type": "bool" }], "name": "setApprovalForAll", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [{ "name": "", "type": "uint256" }], "name": "sellList", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [{ "name": "account", "type": "address" }], "name": "isMinter", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "nft_a", "type": "address" }, { "name": "tokenId", "type": "uint256" }, { "name": "seller", "type": "address" }, { "name": "price", "type": "uint256" }, { "name": "priceDollar", "type": "uint256" }], "name": "sellNFT", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [{ "name": "from", "type": "address" }, { "name": "to", "type": "address" }, { "name": "tokenId", "type": "uint256" }, { "name": "_data", "type": "bytes" }], "name": "safeTransferFrom", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [{ "name": "tokenId", "type": "uint256" }], "name": "getNonCryptoOwner", "outputs": [{ "name": "", "type": "string" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "_newAddress", "type": "address" }], "name": "changeNFTValut", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [{ "name": "", "type": "uint256" }], "name": "_dollarPrice", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "nft_a", "type": "address" }, { "name": "tokenId", "type": "uint256" }, { "name": "sellerId", "type": "string" }, { "name": "price", "type": "uint256" }, { "name": "priceDollar", "type": "uint256" }], "name": "sellNFTNonCrypto", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [{ "name": "tokenId", "type": "uint256" }], "name": "tokenURI", "outputs": [{ "name": "", "type": "string" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [], "name": "init4", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "onSell", "outputs": [{ "name": "", "type": "uint256[]" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": true, "inputs": [{ "name": "owner", "type": "address" }, { "name": "operator", "type": "address" }], "name": "isApprovedForAll", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "main", "type": "uint256" }, { "name": "_author", "type": "uint256" }, { "name": "_platform", "type": "uint256" }], "name": "setValue", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [{ "name": "newOwner", "type": "address" }], "name": "transferOwnership", "outputs": [], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": true, "inputs": [], "name": "authorVault", "outputs": [{ "name": "", "type": "address" }], "payable": false, "stateMutability": "view", "type": "function" }, { "constant": false, "inputs": [{ "name": "to", "type": "address" }, { "name": "tokenURI", "type": "string" }, { "name": "quantity", "type": "uint256" }, { "name": "flag", "type": "bool" }, { "name": "price", "type": "uint256" }, { "name": "ownerId", "type": "string" }, { "name": "royality", "type": "uint256" }, { "name": "priceDollar", "type": "uint256" }], "name": "MintAndSellNFT", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "constant": false, "inputs": [{ "name": "nft_a", "type": "address" }, { "name": "tokenId", "type": "uint256" }, { "name": "buyer", "type": "address" }], "name": "buyNFT", "outputs": [{ "name": "", "type": "bool" }], "payable": false, "stateMutability": "nonpayable", "type": "function" }, { "inputs": [], "payable": false, "stateMutability": "nonpayable", "type": "constructor" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "from", "type": "address" }, { "indexed": true, "name": "token_addr", "type": "address" }, { "indexed": false, "name": "_platform", "type": "address" }, { "indexed": false, "name": "_authorVault", "type": "address" }], "name": "SetAddresses", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "from", "type": "address" }, { "indexed": false, "name": "main", "type": "uint256" }, { "indexed": false, "name": "_author", "type": "uint256" }, { "indexed": false, "name": "_platform", "type": "uint256" }], "name": "SetValue", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "from", "type": "address" }, { "indexed": false, "name": "nft_a", "type": "address" }, { "indexed": false, "name": "tokenId", "type": "uint256" }, { "indexed": false, "name": "seller", "type": "address" }, { "indexed": false, "name": "price", "type": "uint256" }, { "indexed": false, "name": "dollarPrice", "type": "uint256" }], "name": "SellNFT", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "from", "type": "address" }, { "indexed": false, "name": "nft_a", "type": "address" }, { "indexed": false, "name": "tokenId", "type": "uint256" }, { "indexed": false, "name": "buyer", "type": "address" }], "name": "BuyNFT", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "from", "type": "address" }, { "indexed": false, "name": "tokenId", "type": "uint256" }], "name": "CancelSell", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "from", "type": "address" }, { "indexed": false, "name": "tokenId", "type": "uint256" }, { "indexed": false, "name": "newPrice", "type": "uint256" }, { "indexed": false, "name": "newDollarPrice", "type": "uint256" }], "name": "UpdatePrice", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "seller", "type": "address" }, { "indexed": false, "name": "nftContract", "type": "address" }, { "indexed": true, "name": "tokenId", "type": "uint256" }, { "indexed": false, "name": "startPrice", "type": "uint256" }, { "indexed": false, "name": "endTime", "type": "uint256" }], "name": "OnAuction", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "bidder", "type": "address" }, { "indexed": false, "name": "nftContract", "type": "address" }, { "indexed": false, "name": "tokenId", "type": "uint256" }, { "indexed": false, "name": "amount", "type": "uint256" }], "name": "Bid", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "bidder", "type": "address" }, { "indexed": false, "name": "nftContract", "type": "address" }, { "indexed": false, "name": "tokenId", "type": "uint256" }, { "indexed": false, "name": "amount", "type": "uint256" }], "name": "Claim", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "from", "type": "address" }, { "indexed": false, "name": "nft_a", "type": "address" }, { "indexed": false, "name": "tokenId", "type": "uint256" }, { "indexed": false, "name": "buyer", "type": "string" }], "name": "BuyNFTNonCrypto", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "from", "type": "address" }, { "indexed": false, "name": "nft_a", "type": "address" }, { "indexed": false, "name": "tokenId", "type": "uint256" }, { "indexed": false, "name": "seller", "type": "string" }, { "indexed": false, "name": "price", "type": "uint256" }, { "indexed": false, "name": "dollarPrice", "type": "uint256" }], "name": "SellNFTNonCrypto", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "from", "type": "address" }, { "indexed": false, "name": "to", "type": "string" }, { "indexed": false, "name": "tokenURI", "type": "string" }, { "indexed": false, "name": "quantity", "type": "uint256" }, { "indexed": false, "name": "flag", "type": "bool" }], "name": "MintWithTokenURINonCrypto", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "previousOwner", "type": "address" }, { "indexed": true, "name": "newOwner", "type": "address" }], "name": "OwnershipTransferred", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": false, "name": "action", "type": "string" }, { "indexed": true, "name": "from", "type": "address" }, { "indexed": false, "name": "to", "type": "address" }, { "indexed": false, "name": "tokenURI", "type": "string" }, { "indexed": false, "name": "quantity", "type": "uint256" }, { "indexed": false, "name": "flag", "type": "bool" }], "name": "MintWithTokenURI", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "account", "type": "address" }], "name": "MinterAdded", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "account", "type": "address" }], "name": "MinterRemoved", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "from", "type": "address" }, { "indexed": true, "name": "to", "type": "address" }, { "indexed": true, "name": "tokenId", "type": "uint256" }], "name": "Transfer", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "owner", "type": "address" }, { "indexed": true, "name": "approved", "type": "address" }, { "indexed": true, "name": "tokenId", "type": "uint256" }], "name": "Approval", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "name": "owner", "type": "address" }, { "indexed": true, "name": "operator", "type": "address" }, { "indexed": false, "name": "approved", "type": "bool" }], "name": "ApprovalForAll", "type": "event" }]
} else if (networkType === "mainnet") {
  abi = [
    {
      constant: true,
      inputs: [{ name: "interfaceId", type: "bytes4" }],
      name: "supportsInterface",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "name",
      outputs: [{ name: "", type: "string" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "cancelSell",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "getApproved",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "to", type: "address" },
        { name: "tokenId", type: "uint256" },
      ],
      name: "approve",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "totalSupply",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "", type: "address" }],
      name: "_supportNft",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "from", type: "address" },
        { name: "to", type: "address" },
        { name: "tokenId", type: "uint256" },
      ],
      name: "transferFrom",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "owner", type: "address" },
        { name: "index", type: "uint256" },
      ],
      name: "tokenOfOwnerByIndex",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "token_addr", type: "address" },
        { name: "_platform", type: "address" },
        { name: "_authorVault", type: "address" },
      ],
      name: "setAddresses",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "from", type: "address" },
        { name: "to", type: "address" },
        { name: "tokenId", type: "uint256" },
      ],
      name: "safeTransferFrom",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "platform",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "index", type: "uint256" }],
      name: "tokenByIndex",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "ownerOf",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "allTokens",
      outputs: [{ name: "", type: "uint256[]" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "owner", type: "address" }],
      name: "balanceOf",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "renounceOwnership",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "nft", type: "address" }],
      name: "removeSupportNft",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "initialize",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "tokenId", type: "uint256" },
        { name: "newPrice", type: "uint256" },
      ],
      name: "updatePrice",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "owner", type: "address" }],
      name: "tokensOfOwner",
      outputs: [{ name: "", type: "uint256[]" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "owner",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "isOwner",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "symbol",
      outputs: [{ name: "", type: "string" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "account", type: "address" }],
      name: "addMinter",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [],
      name: "renounceMinter",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "getSellDetail",
      outputs: [
        { name: "", type: "address" },
        { name: "", type: "uint256" },
        { name: "", type: "uint256" },
      ],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenIdFunction", type: "uint256" }],
      name: "getAuthor",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "to", type: "address" },
        { name: "approved", type: "bool" },
      ],
      name: "setApprovalForAll",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "nft_a", type: "address" },
        { name: "tokenId", type: "uint256" },
        { name: "seller", type: "address" },
        { name: "price", type: "uint256" },
      ],
      name: "sellNFT",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "", type: "uint256" }],
      name: "sellList",
      outputs: [{ name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "account", type: "address" }],
      name: "isMinter",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "to", type: "address" },
        { name: "tokenURI", type: "string" },
        { name: "quantity", type: "uint256" },
        { name: "flag", type: "bool" },
      ],
      name: "mintWithTokenURI",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "from", type: "address" },
        { name: "to", type: "address" },
        { name: "tokenId", type: "uint256" },
        { name: "_data", type: "bytes" },
      ],
      name: "safeTransferFrom",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "nft", type: "address" }],
      name: "addSupportNft",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [{ name: "tokenId", type: "uint256" }],
      name: "tokenURI",
      outputs: [{ name: "", type: "string" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "onSell",
      outputs: [{ name: "", type: "uint256[]" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { name: "owner", type: "address" },
        { name: "operator", type: "address" },
      ],
      name: "isApprovedForAll",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "main", type: "uint256" },
        { name: "_author", type: "uint256" },
        { name: "_platform", type: "uint256" },
      ],
      name: "setValue",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ name: "newOwner", type: "address" }],
      name: "transferOwnership",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "authorVault",
      outputs: [{ name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { name: "nft_a", type: "address" },
        { name: "tokenId", type: "uint256" },
        { name: "buyer", type: "address" },
      ],
      name: "buyNFT",
      outputs: [{ name: "", type: "bool" }],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "action", type: "string" },
        { indexed: true, name: "from", type: "address" },
        { indexed: true, name: "token_addr", type: "address" },
        { indexed: false, name: "_platform", type: "address" },
        { indexed: false, name: "_authorVault", type: "address" },
      ],
      name: "SetAddresses",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "action", type: "string" },
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "main", type: "uint256" },
        { indexed: false, name: "_author", type: "uint256" },
        { indexed: false, name: "_platform", type: "uint256" },
      ],
      name: "SetValue",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "action", type: "string" },
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "nft_a", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "seller", type: "address" },
        { indexed: false, name: "price", type: "uint256" },
      ],
      name: "SellNFT",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "action", type: "string" },
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "nft_a", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "buyer", type: "address" },
      ],
      name: "BuyNFT",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "action", type: "string" },
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
      ],
      name: "CancelSell",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "action", type: "string" },
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "tokenId", type: "uint256" },
        { indexed: false, name: "newPrice", type: "uint256" },
      ],
      name: "UpdatePrice",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "previousOwner", type: "address" },
        { indexed: true, name: "newOwner", type: "address" },
      ],
      name: "OwnershipTransferred",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: false, name: "action", type: "string" },
        { indexed: true, name: "from", type: "address" },
        { indexed: false, name: "to", type: "address" },
        { indexed: false, name: "tokenURI", type: "string" },
        { indexed: false, name: "quantity", type: "uint256" },
        { indexed: false, name: "flag", type: "bool" },
      ],
      name: "MintWithTokenURI",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, name: "account", type: "address" }],
      name: "MinterAdded",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, name: "account", type: "address" }],
      name: "MinterRemoved",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "from", type: "address" },
        { indexed: true, name: "to", type: "address" },
        { indexed: true, name: "tokenId", type: "uint256" },
      ],
      name: "Transfer",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "owner", type: "address" },
        { indexed: true, name: "approved", type: "address" },
        { indexed: true, name: "tokenId", type: "uint256" },
      ],
      name: "Approval",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, name: "owner", type: "address" },
        { indexed: true, name: "operator", type: "address" },
        { indexed: false, name: "approved", type: "bool" },
      ],
      name: "ApprovalForAll",
      type: "event",
    },
  ];
}

export default abi;
